services:

  # Backend
  - type: web
    name: Yukti-Cli-backend
    runtime: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: LLM_PROVIDER
        value: groq

      - key: GROQ_API_KEY
        sync: false

      - key: GROQ_API_BASE
        value: https://api.groq.com/openai/v1

      - key: GROQ_MODEL
        value: openai/gpt-oss-120b

      - key: OPENROUTER_API_KEY
        sync: false

      - key: OPENROUTER_API_BASE
        value: https://openrouter.ai/api/v1

      - key: OPENROUTER_MODEL
        value: openrouter/auto

    healthCheckPath: /health

  # Frontend
  - type: web
    name: Yukti-Cli
    runtime: static
    rootDir: frontend
    staticPublishPath: .